/**
* nat API
* NAT Service
*
* OpenAPI spec version: 1.0
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/polycube-network/swagger-codegen.git
* branch polycube
*/


// These methods have a default implementation. Your are free to keep it or add your own


#include "../RulePortForwarding.h"



std::shared_ptr<RulePortForwardingEntry> RulePortForwarding::getEntry(const uint32_t &id){
  return RulePortForwardingEntry::getEntry(*this, id);
}

std::vector<std::shared_ptr<RulePortForwardingEntry>> RulePortForwarding::getEntryList(){
  return RulePortForwardingEntry::get(*this);
}

void RulePortForwarding::addEntry(const uint32_t &id, const RulePortForwardingEntryJsonObject &conf){
  RulePortForwardingEntry::create(*this, id, conf);
}

void RulePortForwarding::addEntryList(const std::vector<RulePortForwardingEntryJsonObject> &conf){
  for(auto &i : conf){
    uint32_t id_ = i.getId();
    RulePortForwardingEntry::create(*this, id_,  i);
  }
}

void RulePortForwarding::replaceEntry(const uint32_t &id, const RulePortForwardingEntryJsonObject &conf){
  RulePortForwardingEntry::removeEntry(*this, id);
  uint32_t id_ = conf.getId();
  RulePortForwardingEntry::create(*this, id_, conf);

}

void RulePortForwarding::delEntry(const uint32_t &id){
  RulePortForwardingEntry::removeEntry(*this, id);
}

void RulePortForwarding::delEntryList(){
  RulePortForwardingEntry::remove(*this);
}



