/**
* nat API
* NAT Service
*
* OpenAPI spec version: 1.0
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/polycube-network/swagger-codegen.git
* branch polycube
*/


// These methods have a default implementation. Your are free to keep it or add your own


#include "../RuleSnatEntry.h"


nlohmann::fifo_map<std::string, std::string>  RuleSnatEntry::getKeys() {
  nlohmann::fifo_map<std::string, std::string>  r;

  r["id"] = std::to_string(getId());

  return r;
}







