/**
* simpleforwarder API
* simpleforwarder API generated from simpleforwarder.yang
*
* OpenAPI spec version: 1.0.0
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/polycube-network/swagger-codegen.git
* branch polycube
*/


/* Do not edit this file manually */



#include "SimpleforwarderJsonObject.h"
#include <regex>

namespace io {
namespace swagger {
namespace server {
namespace model {

SimpleforwarderJsonObject::SimpleforwarderJsonObject() {
  m_nameIsSet = false;
  m_portsIsSet = false;
  m_actionsIsSet = false;
}

SimpleforwarderJsonObject::SimpleforwarderJsonObject(const nlohmann::json &val) :
  JsonObjectBase(val) {
  m_nameIsSet = false;
  m_portsIsSet = false;
  m_actionsIsSet = false;


  if (val.count("name")) {
    setName(val.at("name").get<std::string>());
  }

  if (val.count("ports")) {
    for (auto& item : val["ports"]) {
      PortsJsonObject newItem{ item };
      m_ports.push_back(newItem);
    }

    m_portsIsSet = true;
  }

  if (val.count("actions")) {
    for (auto& item : val["actions"]) {
      ActionsJsonObject newItem{ item };
      m_actions.push_back(newItem);
    }

    m_actionsIsSet = true;
  }
}

nlohmann::json SimpleforwarderJsonObject::toJson() const {
  nlohmann::json val = nlohmann::json::object();
  if (!getBase().is_null()) {
    val.update(getBase());
  }

  if (m_nameIsSet) {
    val["name"] = m_name;
  }

  {
    nlohmann::json jsonArray;
    for (auto& item : m_ports) {
      jsonArray.push_back(JsonObjectBase::toJson(item));
    }

    if (jsonArray.size() > 0) {
      val["ports"] = jsonArray;
    }
  }

  {
    nlohmann::json jsonArray;
    for (auto& item : m_actions) {
      jsonArray.push_back(JsonObjectBase::toJson(item));
    }

    if (jsonArray.size() > 0) {
      val["actions"] = jsonArray;
    }
  }

  return val;
}

std::string SimpleforwarderJsonObject::getName() const {
  return m_name;
}

void SimpleforwarderJsonObject::setName(std::string value) {
  m_name = value;
  m_nameIsSet = true;
}

bool SimpleforwarderJsonObject::nameIsSet() const {
  return m_nameIsSet;
}



const std::vector<PortsJsonObject>& SimpleforwarderJsonObject::getPorts() const{
  return m_ports;
}

void SimpleforwarderJsonObject::addPorts(PortsJsonObject value) {
  m_ports.push_back(value);
  m_portsIsSet = true;
}


bool SimpleforwarderJsonObject::portsIsSet() const {
  return m_portsIsSet;
}

void SimpleforwarderJsonObject::unsetPorts() {
  m_portsIsSet = false;
}

const std::vector<ActionsJsonObject>& SimpleforwarderJsonObject::getActions() const{
  return m_actions;
}

void SimpleforwarderJsonObject::addActions(ActionsJsonObject value) {
  m_actions.push_back(value);
  m_actionsIsSet = true;
}


bool SimpleforwarderJsonObject::actionsIsSet() const {
  return m_actionsIsSet;
}

void SimpleforwarderJsonObject::unsetActions() {
  m_actionsIsSet = false;
}


nlohmann::json SimpleforwarderJsonObject::helpKeys() {
  nlohmann::json val = nlohmann::json::object();

  val["name"]["name"] = "name";
  val["name"]["type"] = "key";
  val["name"]["simpletype"] = "string";
  val["name"]["description"] = R"POLYCUBE(Name of the simpleforwarder service)POLYCUBE";
  val["name"]["example"] = R"POLYCUBE(simpleforwarder1)POLYCUBE";

  return val;
}

nlohmann::json SimpleforwarderJsonObject::helpElements() {
  nlohmann::json val = nlohmann::json::object();

  val["uuid"]["name"] = "uuid";
  val["uuid"]["type"] = "leaf"; // Suppose that type is leaf
  val["uuid"]["simpletype"] = "string";
  val["uuid"]["description"] = R"POLYCUBE(UUID of the Cube)POLYCUBE";
  val["uuid"]["example"] = R"POLYCUBE()POLYCUBE";
  val["type"]["name"] = "type";
  val["type"]["type"] = "leaf"; // Suppose that type is leaf
  val["type"]["simpletype"] = "string";
  val["type"]["description"] = R"POLYCUBE(Type of the Cube (TC, XDP_SKB, XDP_DRV))POLYCUBE";
  val["type"]["example"] = R"POLYCUBE(TC)POLYCUBE";
  val["loglevel"]["name"] = "loglevel";
  val["loglevel"]["type"] = "leaf"; // Suppose that type is leaf
  val["loglevel"]["simpletype"] = "string";
  val["loglevel"]["description"] = R"POLYCUBE(Defines the logging level of a service instance, from none (OFF) to the most verbose (TRACE))POLYCUBE";
  val["loglevel"]["example"] = R"POLYCUBE(INFO)POLYCUBE";
  val["ports"]["name"] = "ports";
  val["ports"]["type"] = "leaf"; // Suppose that type is leaf
  val["ports"]["type"] = "list";
  val["ports"]["description"] = R"POLYCUBE(Entry of the ports table)POLYCUBE";
  val["ports"]["example"] = R"POLYCUBE()POLYCUBE";
  val["actions"]["name"] = "actions";
  val["actions"]["type"] = "leaf"; // Suppose that type is leaf
  val["actions"]["type"] = "list";
  val["actions"]["description"] = R"POLYCUBE(Entry of the Actions table)POLYCUBE";
  val["actions"]["example"] = R"POLYCUBE()POLYCUBE";

  return val;
}

nlohmann::json SimpleforwarderJsonObject::helpWritableLeafs() {
  nlohmann::json val = nlohmann::json::object();

  val["loglevel"]["name"] = "loglevel";
  val["loglevel"]["simpletype"] = "string";
  val["loglevel"]["description"] = R"POLYCUBE(Defines the logging level of a service instance, from none (OFF) to the most verbose (TRACE))POLYCUBE";
  val["loglevel"]["example"] = R"POLYCUBE(INFO)POLYCUBE";

  return val;
}

nlohmann::json SimpleforwarderJsonObject::helpComplexElements() {
  nlohmann::json val = nlohmann::json::object();

  val["ports"]["name"] = "ports";
  val["ports"]["type"] = "list";
  val["ports"]["description"] = R"POLYCUBE(Entry of the ports table)POLYCUBE";
  val["ports"]["example"] = R"POLYCUBE()POLYCUBE";
  val["actions"]["name"] = "actions";
  val["actions"]["type"] = "list";
  val["actions"]["description"] = R"POLYCUBE(Entry of the Actions table)POLYCUBE";
  val["actions"]["example"] = R"POLYCUBE()POLYCUBE";

  return val;
}

std::vector<std::string> SimpleforwarderJsonObject::helpActions() {
  std::vector<std::string> val;
  return val;
}

}
}
}
}

