/*
 * firewall API
 *
 * Firewall Service
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ChainResetCountersOutput struct {

	// True if the operation is successful
	Result bool `json:"result,omitempty"`
}
