/*
 * firewall API
 *
 * firewall API generated from firewall.yang
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Firewall struct {
	// Name of the firewall service
	Name string `json:"name,omitempty"`
	// UUID of the Cube
	Uuid string `json:"uuid,omitempty"`
	// Type of the Cube (TC, XDP_SKB, XDP_DRV)
	Type_ string `json:"type,omitempty"`
	ServiceName string `json:"service-name,omitempty"`
	// Logging level of a cube, from none (OFF) to the most verbose (TRACE)
	Loglevel string `json:"loglevel,omitempty"`
	// Enables the Connection Tracking module. Mandatory if connection tracking rules are needed. Default is ON.
	Conntrack string `json:"conntrack,omitempty"`
	// If Connection Tracking is enabled, all packets belonging to ESTABLISHED connections will be forwarded automatically. Default is ON.
	AcceptEstablished string `json:"accept-established,omitempty"`
	// Interactive mode applies new rules immediately; if 'false', the command 'apply-rules' has to be used to apply all the rules at once. Default is TRUE.
	Interactive bool `json:"interactive,omitempty"`
	SessionTable []SessionTable `json:"session-table,omitempty"`
	Chain []Chain `json:"chain,omitempty"`
}
