/**
* nat API
* NAT Service
*
* OpenAPI spec version: 1.0
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/polycube-network/swagger-codegen.git
* branch polycube
*/


/* Do not edit this file manually */

/*
* NattingTableInterface.h
*
*
*/

#pragma once

#include "../serializer/NattingTableJsonObject.h"


using namespace io::swagger::server::model;

class NattingTableInterface {
public:

  virtual void update(const NattingTableJsonObject &conf) = 0;
  virtual NattingTableJsonObject toJsonObject() = 0;

  /// <summary>
  /// Source IP address
  /// </summary>
  virtual std::string getInternalSrc() = 0;

  /// <summary>
  /// Destination IP address
  /// </summary>
  virtual std::string getInternalDst() = 0;

  /// <summary>
  /// Source L4 port number
  /// </summary>
  virtual uint16_t getInternalSport() = 0;

  /// <summary>
  /// Destination L4 port number
  /// </summary>
  virtual uint16_t getInternalDport() = 0;

  /// <summary>
  /// L4 protocol
  /// </summary>
  virtual std::string getProto() = 0;

  /// <summary>
  /// The set of rules that created this mapping
  /// </summary>
  virtual NattingTableOriginatingRuleEnum getOriginatingRule() = 0;
  virtual void setOriginatingRule(const NattingTableOriginatingRuleEnum &value) = 0;

  /// <summary>
  /// Translated IP address
  /// </summary>
  virtual std::string getExternalIp() = 0;
  virtual void setExternalIp(const std::string &value) = 0;

  /// <summary>
  /// Translated L4 port number
  /// </summary>
  virtual uint16_t getExternalPort() = 0;
  virtual void setExternalPort(const uint16_t &value) = 0;
};

