/**
* nat API
* NAT Service
*
* OpenAPI spec version: 1.0
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/polycube-network/swagger-codegen.git
* branch polycube
*/


/* Do not edit this file manually */

#include "api/NatApiImpl.h"
#define SERVICE_PYANG_GIT ""
#define SERVICE_SWAGGER_CODEGEN_GIT "c757d44b71d48df9e381fc8d35ea69bd12268127/c757d44"

#include <polycube/services/shared_library.h>
#include "../datamodel/nat.h" // generated from datamodel

extern "C" const char *data_model() {
  return nat_datamodel.c_str();
}
