#!/bin/bash

# check if polycubed is alive
polycubed_alive=$(ps -el | grep polycubed)
if [ -z "$polycubed_alive" ]; then
    echo "polycubed is NOT running."
    echo "please launch it using ..."
    echo "'sudo polycubed'"
    exit 1
    # sudo polycubed
else
    echo "polycubed already launched ..."
fi

ret=$(polycubectl iptables pcn-iptables show)
ret=$(echo $?)

if [ $ret -ne 0 ]
    then
        echo "Launching pcn-iptables ..."
        polycubectl iptables add pcn-iptables type=XDP_DRV
        echo "DONE! pcn-iptables launched"
        exit 0
else
    echo "pcn-iptables already launched ..."
fi

echo "DONE"
