/**
* router API
* router API generated from router.yang
*
* OpenAPI spec version: 1.0.0
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/polycube-network/swagger-codegen.git
* branch polycube
*/


/* Do not edit this file manually */



#include "RouterJsonObject.h"
#include <regex>

namespace io {
namespace swagger {
namespace server {
namespace model {

RouterJsonObject::RouterJsonObject() {
  m_nameIsSet = false;
  m_portsIsSet = false;
  m_routeIsSet = false;
  m_arpEntryIsSet = false;
}

RouterJsonObject::RouterJsonObject(const nlohmann::json &val) :
  JsonObjectBase(val) {
  m_nameIsSet = false;
  m_portsIsSet = false;
  m_routeIsSet = false;
  m_arpEntryIsSet = false;


  if (val.count("name")) {
    setName(val.at("name").get<std::string>());
  }

  if (val.count("ports")) {
    for (auto& item : val["ports"]) {
      PortsJsonObject newItem{ item };
      m_ports.push_back(newItem);
    }

    m_portsIsSet = true;
  }

  if (val.count("route")) {
    for (auto& item : val["route"]) {
      RouteJsonObject newItem{ item };
      m_route.push_back(newItem);
    }

    m_routeIsSet = true;
  }

  if (val.count("arp-entry")) {
    for (auto& item : val["arp-entry"]) {
      ArpEntryJsonObject newItem{ item };
      m_arpEntry.push_back(newItem);
    }

    m_arpEntryIsSet = true;
  }
}

nlohmann::json RouterJsonObject::toJson() const {
  nlohmann::json val = nlohmann::json::object();
  if (!getBase().is_null()) {
    val.update(getBase());
  }

  if (m_nameIsSet) {
    val["name"] = m_name;
  }

  {
    nlohmann::json jsonArray;
    for (auto& item : m_ports) {
      jsonArray.push_back(JsonObjectBase::toJson(item));
    }

    if (jsonArray.size() > 0) {
      val["ports"] = jsonArray;
    }
  }

  {
    nlohmann::json jsonArray;
    for (auto& item : m_route) {
      jsonArray.push_back(JsonObjectBase::toJson(item));
    }

    if (jsonArray.size() > 0) {
      val["route"] = jsonArray;
    }
  }

  {
    nlohmann::json jsonArray;
    for (auto& item : m_arpEntry) {
      jsonArray.push_back(JsonObjectBase::toJson(item));
    }

    if (jsonArray.size() > 0) {
      val["arp-entry"] = jsonArray;
    }
  }

  return val;
}

std::string RouterJsonObject::getName() const {
  return m_name;
}

void RouterJsonObject::setName(std::string value) {
  m_name = value;
  m_nameIsSet = true;
}

bool RouterJsonObject::nameIsSet() const {
  return m_nameIsSet;
}



const std::vector<PortsJsonObject>& RouterJsonObject::getPorts() const{
  return m_ports;
}

void RouterJsonObject::addPorts(PortsJsonObject value) {
  m_ports.push_back(value);
  m_portsIsSet = true;
}


bool RouterJsonObject::portsIsSet() const {
  return m_portsIsSet;
}

void RouterJsonObject::unsetPorts() {
  m_portsIsSet = false;
}

const std::vector<RouteJsonObject>& RouterJsonObject::getRoute() const{
  return m_route;
}

void RouterJsonObject::addRoute(RouteJsonObject value) {
  m_route.push_back(value);
  m_routeIsSet = true;
}


bool RouterJsonObject::routeIsSet() const {
  return m_routeIsSet;
}

void RouterJsonObject::unsetRoute() {
  m_routeIsSet = false;
}

const std::vector<ArpEntryJsonObject>& RouterJsonObject::getArpEntry() const{
  return m_arpEntry;
}

void RouterJsonObject::addArpEntry(ArpEntryJsonObject value) {
  m_arpEntry.push_back(value);
  m_arpEntryIsSet = true;
}


bool RouterJsonObject::arpEntryIsSet() const {
  return m_arpEntryIsSet;
}

void RouterJsonObject::unsetArpEntry() {
  m_arpEntryIsSet = false;
}


nlohmann::json RouterJsonObject::helpKeys() {
  nlohmann::json val = nlohmann::json::object();

  val["name"]["name"] = "name";
  val["name"]["type"] = "key";
  val["name"]["simpletype"] = "string";
  val["name"]["description"] = R"POLYCUBE(Name of the router service)POLYCUBE";
  val["name"]["example"] = R"POLYCUBE(router1)POLYCUBE";

  return val;
}

nlohmann::json RouterJsonObject::helpElements() {
  nlohmann::json val = nlohmann::json::object();

  val["uuid"]["name"] = "uuid";
  val["uuid"]["type"] = "leaf"; // Suppose that type is leaf
  val["uuid"]["simpletype"] = "string";
  val["uuid"]["description"] = R"POLYCUBE(UUID of the Cube)POLYCUBE";
  val["uuid"]["example"] = R"POLYCUBE()POLYCUBE";
  val["type"]["name"] = "type";
  val["type"]["type"] = "leaf"; // Suppose that type is leaf
  val["type"]["simpletype"] = "string";
  val["type"]["description"] = R"POLYCUBE(Type of the Cube (TC, XDP_SKB, XDP_DRV))POLYCUBE";
  val["type"]["example"] = R"POLYCUBE(TC)POLYCUBE";
  val["loglevel"]["name"] = "loglevel";
  val["loglevel"]["type"] = "leaf"; // Suppose that type is leaf
  val["loglevel"]["simpletype"] = "string";
  val["loglevel"]["description"] = R"POLYCUBE(Defines the logging level of a service instance, from none (OFF) to the most verbose (TRACE))POLYCUBE";
  val["loglevel"]["example"] = R"POLYCUBE(INFO)POLYCUBE";
  val["ports"]["name"] = "ports";
  val["ports"]["type"] = "leaf"; // Suppose that type is leaf
  val["ports"]["type"] = "list";
  val["ports"]["description"] = R"POLYCUBE(Entry of the ports table)POLYCUBE";
  val["ports"]["example"] = R"POLYCUBE()POLYCUBE";
  val["route"]["name"] = "route";
  val["route"]["type"] = "leaf"; // Suppose that type is leaf
  val["route"]["type"] = "list";
  val["route"]["description"] = R"POLYCUBE(Entry associated with the routing table)POLYCUBE";
  val["route"]["example"] = R"POLYCUBE()POLYCUBE";
  val["arp-entry"]["name"] = "arp-entry";
  val["arp-entry"]["type"] = "leaf"; // Suppose that type is leaf
  val["arp-entry"]["type"] = "list";
  val["arp-entry"]["description"] = R"POLYCUBE(Entry associated with the ARP table)POLYCUBE";
  val["arp-entry"]["example"] = R"POLYCUBE()POLYCUBE";

  return val;
}

nlohmann::json RouterJsonObject::helpWritableLeafs() {
  nlohmann::json val = nlohmann::json::object();

  val["loglevel"]["name"] = "loglevel";
  val["loglevel"]["simpletype"] = "string";
  val["loglevel"]["description"] = R"POLYCUBE(Defines the logging level of a service instance, from none (OFF) to the most verbose (TRACE))POLYCUBE";
  val["loglevel"]["example"] = R"POLYCUBE(INFO)POLYCUBE";

  return val;
}

nlohmann::json RouterJsonObject::helpComplexElements() {
  nlohmann::json val = nlohmann::json::object();

  val["ports"]["name"] = "ports";
  val["ports"]["type"] = "list";
  val["ports"]["description"] = R"POLYCUBE(Entry of the ports table)POLYCUBE";
  val["ports"]["example"] = R"POLYCUBE()POLYCUBE";
  val["route"]["name"] = "route";
  val["route"]["type"] = "list";
  val["route"]["description"] = R"POLYCUBE(Entry associated with the routing table)POLYCUBE";
  val["route"]["example"] = R"POLYCUBE()POLYCUBE";
  val["arp-entry"]["name"] = "arp-entry";
  val["arp-entry"]["type"] = "list";
  val["arp-entry"]["description"] = R"POLYCUBE(Entry associated with the ARP table)POLYCUBE";
  val["arp-entry"]["example"] = R"POLYCUBE()POLYCUBE";

  return val;
}

std::vector<std::string> RouterJsonObject::helpActions() {
  std::vector<std::string> val;
  return val;
}

}
}
}
}

