/**
* k8switch API
* LoadBalancer Reverse-Proxy Service
*
* OpenAPI spec version: 2.0.0
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/polycube-network/swagger-codegen.git
* branch polycube
*/


/* Do not edit this file manually */

/*
* ArpEntryInterface.h
*
*
*/

#pragma once

#include "../serializer/ArpEntryJsonObject.h"


using namespace io::swagger::server::model;

class ArpEntryInterface {
public:

  virtual void update(const ArpEntryJsonObject &conf) = 0;
  virtual ArpEntryJsonObject toJsonObject() = 0;

  /// <summary>
  /// Destination IP address
  /// </summary>
  virtual std::string getAddress() = 0;

  /// <summary>
  /// Destination MAC address
  /// </summary>
  virtual std::string getMac() = 0;
  virtual void setMac(const std::string &value) = 0;
};

