/**
* dyntmon API generated from dyntmon.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */



#include "MetricsJsonObject.h"
#include <regex>

namespace polycube {
namespace service {
namespace model {

MetricsJsonObject::MetricsJsonObject() {
  m_nameIsSet = false;
  m_valueIsSet = false;
  m_timestampIsSet = false;
}

MetricsJsonObject::MetricsJsonObject(const nlohmann::json &val) :
  JsonObjectBase(val) {
  m_nameIsSet = false;
  m_valueIsSet = false;
  m_timestampIsSet = false;


  if (val.count("name")) {
    setName(val.at("name").get<std::string>());
  }

  if (val.count("value")) {
    setValue(val.at("value").get<std::string>());
  }

  if (val.count("timestamp")) {
    setTimestamp(val.at("timestamp").get<int64_t>());
  }
}

nlohmann::json MetricsJsonObject::toJson() const {
  nlohmann::json val = nlohmann::json::object();
  if (!getBase().is_null()) {
    val.update(getBase());
  }

  if (m_nameIsSet) {
    val["name"] = m_name;
  }

  if (m_valueIsSet) {
    val["value"] = m_value;
  }

  if (m_timestampIsSet) {
    val["timestamp"] = m_timestamp;
  }

  return val;
}

std::string MetricsJsonObject::getName() const {
  return m_name;
}

void MetricsJsonObject::setName(std::string value) {
  m_name = value;
  m_nameIsSet = true;
}

bool MetricsJsonObject::nameIsSet() const {
  return m_nameIsSet;
}



std::string MetricsJsonObject::getValue() const {
  return m_value;
}

void MetricsJsonObject::setValue(std::string value) {
  m_value = value;
  m_valueIsSet = true;
}

bool MetricsJsonObject::valueIsSet() const {
  return m_valueIsSet;
}

void MetricsJsonObject::unsetValue() {
  m_valueIsSet = false;
}

int64_t MetricsJsonObject::getTimestamp() const {
  return m_timestamp;
}

void MetricsJsonObject::setTimestamp(int64_t value) {
  m_timestamp = value;
  m_timestampIsSet = true;
}

bool MetricsJsonObject::timestampIsSet() const {
  return m_timestampIsSet;
}

void MetricsJsonObject::unsetTimestamp() {
  m_timestampIsSet = false;
}


}
}
}

