/**
* policer API generated from policer.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* PolicerJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"

#include "DefaultContractJsonObject.h"
#include "ContractJsonObject.h"
#include <vector>
#include "polycube/services/cube.h"

namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  PolicerJsonObject : public JsonObjectBase {
public:
  PolicerJsonObject();
  PolicerJsonObject(const nlohmann::json &json);
  ~PolicerJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// Name of the policer service
  /// </summary>
  std::string getName() const;
  void setName(std::string value);
  bool nameIsSet() const;

  /// <summary>
  /// Contract applied to traffic not matching any of the specified classes (default: PASS)
  /// </summary>
  DefaultContractJsonObject getDefaultContract() const;
  void setDefaultContract(DefaultContractJsonObject value);
  bool defaultContractIsSet() const;
  void unsetDefaultContract();

  /// <summary>
  /// Contract applied to a specific class of traffic
  /// </summary>
  const std::vector<ContractJsonObject>& getContract() const;
  void addContract(ContractJsonObject value);
  bool contractIsSet() const;
  void unsetContract();

private:
  std::string m_name;
  bool m_nameIsSet;
  DefaultContractJsonObject m_defaultContract;
  bool m_defaultContractIsSet;
  std::vector<ContractJsonObject> m_contract;
  bool m_contractIsSet;
};

}
}
}

