/**
* lbdsr API
* lbdsr API generated from lbdsr.yang
*
* OpenAPI spec version: 1.0.0
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/polycube-network/swagger-codegen.git
* branch polycube
*/


// These methods have a default implementation. Your are free to keep it or add your own


#include "../Lbdsr.h"



std::shared_ptr<Ports> Lbdsr::getPorts(const std::string &name){
  return Ports::getEntry(*this, name);
}

std::vector<std::shared_ptr<Ports>> Lbdsr::getPortsList(){
  return Ports::get(*this);
}

void Lbdsr::addPorts(const std::string &name, const PortsJsonObject &conf){
  Ports::create(*this, name, conf);
}

void Lbdsr::addPortsList(const std::vector<PortsJsonObject> &conf){
  for(auto &i : conf){
    std::string name_ = i.getName();
    Ports::create(*this, name_,  i);
  }
}

void Lbdsr::replacePorts(const std::string &name, const PortsJsonObject &conf){
  Ports::removeEntry(*this, name);
  std::string name_ = conf.getName();
  Ports::create(*this, name_, conf);

}

void Lbdsr::delPorts(const std::string &name){
  Ports::removeEntry(*this, name);
}

void Lbdsr::delPortsList(){
  Ports::remove(*this);
}

std::shared_ptr<Frontend> Lbdsr::getFrontend(){
  return Frontend::getEntry(*this);
}

void Lbdsr::addFrontend(const FrontendJsonObject &value){
  Frontend::create(*this, value);
}

void Lbdsr::replaceFrontend(const FrontendJsonObject &conf){
  Frontend::removeEntry(*this);
  Frontend::create(*this, conf);
}

void Lbdsr::delFrontend(){
  Frontend::removeEntry(*this);
}


std::shared_ptr<Backend> Lbdsr::getBackend(){
  return Backend::getEntry(*this);
}

void Lbdsr::addBackend(const BackendJsonObject &value){
  Backend::create(*this, value);
}

void Lbdsr::replaceBackend(const BackendJsonObject &conf){
  Backend::removeEntry(*this);
  Backend::create(*this, conf);
}

void Lbdsr::delBackend(){
  Backend::removeEntry(*this);
}




