IMAGE_NAME = "ubuntu/bionic64"
BRIDGE_NIC = "enp1s0f0"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = true

    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end
    config.vm.define "k8s-1-master--1" do |master|
        master.vm.box = IMAGE_NAME
        # change the bridge interface to match the one on your host machine
        master.vm.network "public_network", bridge: BRIDGE_NIC, ip: "192.168.1.10", netmask: "255.255.254.0"
        master.vm.hostname = "k8s-master"
        master.vm.provision "ansible" do |ansible|
            # Configures the ssh-key
            ansible.playbook = "kubernetes-playbooks/vagrant-ssh-key.yml"
             ansible.extra_vars = {
                pub_key_path: "~/.ssh/vagrant_machines.pub"
            }
        end
    end

    config.vm.define "k8s-1-node-1" do |node|
        node.vm.box = IMAGE_NAME
        # change the bridge interface to match the one on your host machine
        node.vm.network "public_network", bridge: BRIDGE_NIC, ip: "192.168.1.11", netmask: "255.255.254.0"
        node.vm.hostname = "node-1"
        node.vm.provision "ansible" do |ansible|
            # Configures the ssh-key
            ansible.playbook = "kubernetes-playbooks/vagrant-ssh-key.yml"
            ansible.extra_vars = {
                pub_key_path: "~/.ssh/vagrant_machines.pub"
            }
        end
    end
    config.vm.define "k8s-1-node-2" do |node|
        node.vm.box = IMAGE_NAME
        # change the bridge interface to match the one on your host machine
        node.vm.network "public_network", bridge: BRIDGE_NIC, ip: "192.168.1.12", netmask: "255.255.254.0"
        node.vm.hostname = "node-2"
        node.vm.provision "ansible" do |ansible|
            # Configures the ssh-key
            ansible.playbook = "kubernetes-playbooks/vagrant-ssh-key.yml"
            ansible.extra_vars = {
                pub_key_path: "~/.ssh/vagrant_machines.pub"
            }
        end
    end
end
