/**
* simplebridge API
* Simple L2 Bridge Service
*
* OpenAPI spec version: 1.0.0
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/polycube-network/swagger-codegen.git
* branch polycube
*/


/* Do not edit this file manually */

/*
* FdbEntryJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"


namespace io {
namespace swagger {
namespace server {
namespace model {


/// <summary>
///
/// </summary>
class  FdbEntryJsonObject : public JsonObjectBase {
public:
  FdbEntryJsonObject();
  virtual ~FdbEntryJsonObject();

  /////////////////////////////////////////////
  /// JsonObjectBase overrides

  void validateKeys() override;
  void validateMandatoryFields() override;
  void validateParams() override;

  nlohmann::json toJson() const override;
  void fromJson(nlohmann::json& json) override;

  static nlohmann::json helpKeys();
  static nlohmann::json helpElements();
  static nlohmann::json helpWritableLeafs();
  static nlohmann::json helpComplexElements();
  static std::vector<std::string> helpActions();
  /////////////////////////////////////////////
  /// FdbEntryJsonObject members

  /// <summary>
  /// Address of the filtering database entry
  /// </summary>
  std::string getAddress() const;
  void setAddress(std::string value);
  bool addressIsSet() const;
  void unsetAddress();

  /// <summary>
  /// Output port name
  /// </summary>
  std::string getPort() const;
  void setPort(std::string value);
  bool portIsSet() const;
  void unsetPort();

  /// <summary>
  /// Age of the current filtering database entry
  /// </summary>
  uint32_t getAge() const;
  void setAge(uint32_t value);
  bool ageIsSet() const;
  void unsetAge();


protected:
  std::string m_address;
  bool m_addressIsSet;
  std::string m_port;
  bool m_portIsSet;
  uint32_t m_age;
  bool m_ageIsSet;

  std::vector<std::string> allowedParameters_{ "address", "port", "age" };
};

}
}
}
}

