/**
* simplebridge API generated from simplebridge.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* FdbEntryJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"


namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  FdbEntryJsonObject : public JsonObjectBase {
public:
  FdbEntryJsonObject();
  FdbEntryJsonObject(const nlohmann::json &json);
  ~FdbEntryJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// Address of the filtering database entry
  /// </summary>
  std::string getAddress() const;
  void setAddress(std::string value);
  bool addressIsSet() const;

  /// <summary>
  /// Output port name
  /// </summary>
  std::string getPort() const;
  void setPort(std::string value);
  bool portIsSet() const;

  /// <summary>
  /// Age of the current filtering database entry
  /// </summary>
  uint32_t getAge() const;
  void setAge(uint32_t value);
  bool ageIsSet() const;
  void unsetAge();

private:
  std::string m_address;
  bool m_addressIsSet;
  std::string m_port;
  bool m_portIsSet;
  uint32_t m_age;
  bool m_ageIsSet;
};

}
}
}

