/**
* dynmon API generated from dynmon.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* DataplaneMetricsOpenMetricsMetadataBase.h
*
*
*/

#pragma once

#include "../serializer/DataplaneMetricsOpenMetricsMetadataJsonObject.h"

#include "../DataplaneMetricsOpenMetricsMetadataLabels.h"





#include <spdlog/spdlog.h>

using namespace polycube::service::model;

class DataplaneMetrics;

class DataplaneMetricsOpenMetricsMetadataBase {
 public:
  
  DataplaneMetricsOpenMetricsMetadataBase(DataplaneMetrics &parent);
  
  virtual ~DataplaneMetricsOpenMetricsMetadataBase();
  virtual void update(const DataplaneMetricsOpenMetricsMetadataJsonObject &conf);
  virtual DataplaneMetricsOpenMetricsMetadataJsonObject toJsonObject();

  /// <summary>
  /// Metric description
  /// </summary>
  virtual std::string getHelp() = 0;

  /// <summary>
  /// Metric type
  /// </summary>
  virtual DataplaneMetricsOpenMetricsMetadataTypeEnum getType() = 0;

  /// <summary>
  /// Label attached to the metric
  /// </summary>
  virtual std::shared_ptr<DataplaneMetricsOpenMetricsMetadataLabels> getLabels(const std::string &name) = 0;
  virtual std::vector<std::shared_ptr<DataplaneMetricsOpenMetricsMetadataLabels>> getLabelsList() = 0;
  virtual void addLabels(const std::string &name, const DataplaneMetricsOpenMetricsMetadataLabelsJsonObject &conf) = 0;
  virtual void addLabelsList(const std::vector<DataplaneMetricsOpenMetricsMetadataLabelsJsonObject> &conf);
  virtual void replaceLabels(const std::string &name, const DataplaneMetricsOpenMetricsMetadataLabelsJsonObject &conf);
  virtual void delLabels(const std::string &name) = 0;
  virtual void delLabelsList();

  std::shared_ptr<spdlog::logger> logger();
 protected:
  DataplaneMetrics &parent_;
};
