/**
* classifier API generated from classifier.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

#include "api/ClassifierApiImpl.h"
#include "../datamodel/classifier.h" // generated from datamodel

#define SERVICE_PYANG_GIT ""
#define SERVICE_SWAGGER_CODEGEN_GIT "master/f3b9193"

#include <polycube/services/shared_library.h>

extern "C" const char *data_model() {
  return classifier_datamodel.c_str();
}
