/**
 * bridge API generated from bridge.yang
 *
 * NOTE: This file is auto generated by polycube-codegen
 * https://github.com/polycube-network/polycube-codegen
 */

/* Do not edit this file manually */

/*
 * PortsTrunkAllowedBase.h
 *
 *
 */

#pragma once

#include "../serializer/PortsTrunkAllowedJsonObject.h"

#include <spdlog/spdlog.h>

using namespace polycube::service::model;

class PortsTrunk;

class PortsTrunkAllowedBase {
 public:
  PortsTrunkAllowedBase(PortsTrunk &parent);

  virtual ~PortsTrunkAllowedBase();
  virtual void update(const PortsTrunkAllowedJsonObject &conf);
  virtual PortsTrunkAllowedJsonObject toJsonObject();

  /// <summary>
  /// Allowed vlan
  /// </summary>
  virtual uint16_t getVlanid() = 0;

  std::shared_ptr<spdlog::logger> logger();

 protected:
  PortsTrunk &parent_;
};
