# This is a basic workflow to help in CI
name: Build & Push Workflow

# Controls when the action will run. Triggers the workflow on schedule events
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  #schedule:
    # Runs every 15 minutes past every hour on Mon, Tue, Wed, Thu and Fri
    #- cron: '*/15 * * * 1-5'
env:
  DOCKER_IMAGE_NAME: polycube
# This workflow is made by two jobs that run sequentially
jobs:
  # The first job deal with building the application
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Build strategies
    strategy:
      matrix:
        # For docker default mode
        mode: ['default', 'pcn-k8s', 'pcn-iptables']
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository (default master)
      - uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false

      - name: Configure step outputs
        id: configure
        run: |
          # The ref of the commit to checkout (do not use the merge commit if pull request)
          [[ "${{ github.event_name }}" == "pull_request" ]] && \
            echo "::set-output name=ref::${{ github.event.pull_request.head.sha }}" || \
            echo "::set-output name=ref::${{ github.sha }}"
          # The suffix to append to the repository name if not triggered by a push to master
          [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/master" ]] && \
            echo "::set-output name=repo-suffix::" || \
            echo "::set-output name=repo-suffix::-dev"
          # Do not push the resulting images to DockerHub if triggered by a pull request
          [[ "${{ github.event_name }}" == "pull_request" ]] && \
            echo "::set-output name=repo-push::false" || \
            echo "::set-output name=repo-push::true"
          
          echo "::set-output name=repo-name::${{ github.repository_owner }}/polycubebot/${{ env.DOCKER_IMAGE_NAME }}-${{ matrix.mode }}"

      - name: Docker login to Github registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      
      - name: Build and push
        id: docker_build
        run: |
          sudo DOCKER_BUILDKIT=1 docker build . -t "ghcr.io/${{ steps.configure.outputs.repo-name }}${{ steps.configure.outputs.repo-suffix }}:latest" --build-arg DEFAULT_MODE=${{ matrix.mode }}
          sudo docker push ghcr.io/${{ steps.configure.outputs.repo-name }}${{ steps.configure.outputs.repo-suffix }}:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
